# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 237ffcbb6f04f3bc825803243fb2728517e9455e74a076b1a77f016db1965e0a6f8bf892eb51b07a1dc4d661ac03f1bcfd99a52db8825f39bead09b7d473c812

test:
  secret_key_base: bc8ff629b413f14f65fca76eb6e47a60c31c32d41327cb5e352cff0660150902c57ed6c9215dc4779af36f9cd17217fcbb4084a3f2ea8a0e3b9793767e52405a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
